language: python
python:
- '3.8'
services:
- postgresql
addons:
  ssh_known_hosts: myacademysut.ir
env:
- DJANGO=3.0.5

before_install:
- export DJANGO_SETTINGS_MODULE='MyAcademy.test_settings'
install:
- pip install -r requirements.txt

before_script:
- psql -c 'create database travis_ci_db;' -U postgres
script:
- python manage.py migrate
- python manage.py test
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod +x deploy.sh
- cp deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
