language: python
dist: bionic
python:
- '3.8'
services:
- postgresql
env:
- DJANGO=3.0.5
before_install:
- export DJANGO_SETTINGS_MODULE='MyAcademy.test_settings'
install:
- pip install -r requirements.txt

before_script:
- psql -c 'create database travis_ci_db;' -U postgres
script:
- python manage.py migrate
- python manage.py test

