# Generated by Django 3.0.5 on 2020-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptrating',
            options={'verbose_name': 'امتیاز دانشکده', 'verbose_name_plural': 'امتیازهای دانشکده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='profrating',
            options={'verbose_name': 'امتیاز استاد', 'verbose_name_plural': 'امتیازهای اساتید'},
        ),
        migrations.AlterModelOptions(
            name='unirating',
            options={'verbose_name': 'امتیاز دانشگاه', 'verbose_name_plural': 'امتیازهای دانشگاه\u200cها'},
        ),
    ]
