# Generated by Django 3.0.5 on 2020-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20200528_1820'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deptrating',
            constraint=models.UniqueConstraint(fields=('user', 'dept'), name='unique_dept_rating'),
        ),
        migrations.AddConstraint(
            model_name='profrating',
            constraint=models.UniqueConstraint(fields=('user', 'prof'), name='unique_prof_rating'),
        ),
        migrations.AddConstraint(
            model_name='unirating',
            constraint=models.UniqueConstraint(fields=('user', 'uni'), name='unique_uni_rating'),
        ),
    ]
