# Generated by Django 3.0.5 on 2020-06-03 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0003_auto_20200531_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptrating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
        migrations.AddField(
            model_name='deptrating',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='profrating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
        migrations.AddField(
            model_name='profrating',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='unirating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
        migrations.AddField(
            model_name='unirating',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.CreateModel(
            name='UniRatingReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.UniRating', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfRatingReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.ProfRating', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeptRatingReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.DeptRating', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
