# Generated by Django 3.0.5 on 2020-06-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20200604_0116'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deptratingreaction',
            constraint=models.UniqueConstraint(fields=('user', 'rating'), name='unique_deptcomment_like'),
        ),
        migrations.AddConstraint(
            model_name='profratingreaction',
            constraint=models.UniqueConstraint(fields=('user', 'rating'), name='unique_profcomment_like'),
        ),
        migrations.AddConstraint(
            model_name='uniratingreaction',
            constraint=models.UniqueConstraint(fields=('user', 'rating'), name='unique_unicomment_like'),
        ),
    ]
