# Generated by Django 3.0.5 on 2020-07-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_advancedblogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedblogpage',
            name='author',
        ),
    ]
