# Generated by Django 3.0.5 on 2020-07-25 12:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_advancedblogpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedblogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_slider', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Slider'))]),
        ),
    ]
