# Generated by Django 3.0.5 on 2020-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200725_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedblogpage',
            name='intro',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
