# Generated by Django 3.0.5 on 2020-05-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.Entity')),
                ('name', models.CharField(max_length=30)),
                ('university_name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.Entity')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department_name', models.CharField(blank=True, max_length=30)),
                ('university_name', models.CharField(blank=True, max_length=30)),
                ('score', models.IntegerField()),
            ],
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.Entity')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
            bases=('entities.entity',),
        ),
    ]
