# Generated by Django 3.0.5 on 2020-05-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'دانشکده', 'verbose_name_plural': 'دانشکده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'دانشگاه', 'verbose_name_plural': 'دانشگاه\u200cها'},
        ),
    ]
