# Generated by Django 3.0.5 on 2020-05-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('entities', '0002_auto_20200508_2247'),
	]

	operations = [
		migrations.AlterField(
			model_name='department',
			name='picture',
			field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to='profile_pictures'),
		),
		migrations.AlterField(
			model_name='professor',
			name='picture',
			field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to='profile_pictures'),
		),
		migrations.AlterField(
			model_name='university',
			name='address',
			field=models.CharField(blank=True, max_length=100, verbose_name='آدرس'),
		),
		migrations.AlterField(
			model_name='university',
			name='name',
			field=models.CharField(max_length=30, unique=True, verbose_name='name'),
		),
		migrations.AlterField(
			model_name='university',
			name='picture',
			field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to='profile_pictures'),
		),
	]
