# Generated by Django 3.0.5 on 2020-05-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20200510_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='my_university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.University', verbose_name='دانشگاه'),
        ),
    ]
